services:
  db:
    image: postgres:14.9
    restart: always
    networks:
      - default
    ports:
      - "5432:5432"
    env_file:
      - path: .env
        required: true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  
  initialdata:
    build:
      context: ./backend
      dockerfile: Dockerfile.initialdata
    env_file:
      - path: .env
        required: true
    depends_on:
      db:
        condition: service_healthy
        restart: true
    networks:
      - default
    restart: on-failure
    
  backend:
    env_file:
      - path: .env
        required: true
    restart: always
    networks:
      - default
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:  
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    volumes:
      - json_data:/json_data

networks:
  default:
    driver: bridge

volumes:
  json_data: