services:
  db:
    image: postgres
    env_file:
      - .env
    restart: always
    networks:
      - default
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: idealogapi
    
  backend:
    env_file:
        - .env
    restart: always
    networks:
      - default
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=idealogapi

    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:  
      - "8000:8000"
    depends_on:
      - db

networks:
  default:
    driver: bridge

