services:
  backend:
    restart: always
    networks:
      - default
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/idealog
    build:
      context: .
      dockerfile: Dockerfile

networks:
  default:
    driver: bridge